# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-sage" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2c8dd8937641edc895d5d237e1b9210388870db69a49a5e28fc770f8c759ba9e"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f50e3847a798195908a41e296f587e0168e5b012bdba8e62af50f81eae571171"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b2597db7c083faab32c3cb85acd8fe3728f2c78621c50392ff503bac8205acf"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a0abdfd0545615456e643551e112a50bc897ce8b20936114cde8873dc78e757"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-sage"
  desc "Summarize what each tmux window is doing with an LLM and set it as the window name"
  homepage "https://github.com/hiroakis/tmux-sage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmux-sage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-sage"]
    end
  end

  # No zap stanza required

end
