# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-sage" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "cae5dede58e93d2170db39b4241b9d5bfa0f5ea7feb5f884b190d2a8d2d4564c"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac6858e8b0ecb0d2679e486216bc3e29ca25883b77f7f658205117da5b8d22e5"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "93f4a16c5561841a12fdffb7d7e22c7d4175379c6f041e2e1677e1f1ef23c497"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c71b6c7af2d4ea3d354f51c6919997169cc584a02dbec4305f16b20f548e21e8"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-sage"
  desc "Summarize what each tmux window is doing with an LLM and set it as the window name"
  homepage "https://github.com/hiroakis/tmux-sage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmux-sage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-sage"]
    end
  end

  # No zap stanza required

end
