# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-sage" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "27936e6391f496c061fe8ee733bee8a80232bfb7194083d90007701ff26fe7a8"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8adb565636f81fd786c2db0261509c95a0da9a0e6715b24d620d467bcec3d0e5"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "027ff11caae9b8eeec507635f5199d38c927bd21911722a6e43bb831c76880d4"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a15120805a2c92e38114e2cdb687ee070daa174acb9a2230005830c44fb9c7dc"
      url "https://github.com/hiroakis/tmux-sage/releases/download/v#{version}/tmux-sage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-sage"
  desc "Summarize what each tmux window is doing with an LLM and set it as the window name"
  homepage "https://github.com/hiroakis/tmux-sage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmux-sage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-sage"]
    end
  end

  # No zap stanza required

end
